language: python
python:
  - "3.9"
install:
  - nvm install 14.15.3
  - npm install -g aws-cdk
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - coverage run --source="app,deadnets,tests" -m unittest discover
after_success:
  - coveralls
  - cdk deploy
