language: python
python:
  - "3.9"
install:
  - nvm install 14.15.3
  - npm install -g aws-cdk
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - coverage run -m unittest discover
  - coverage report -m
after_success:
  - coveralls
